epochs: 10
lr: 0.0001
ckpt_frequency: 5  # Save checkpoint every 5 epochs
resume_from_last: false  # resume from last ckpt in exp dir if true for epochs (could be improved)
accelerator: "auto"  # Lightning Fabric: "cpu", "gpu", "tpu", or "auto"
devices: "auto"  # Number of devices (e.g., 2 for 2 GPUs)
precision: "32-true"  # Mixed precision: "16-mixed", "bf16-mixed", or "32-true"

logging:
  epoch_frequency: 1
  image_frequency: 1  # Log images every epoch